name = "backend-server"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-05-08"
# compatibility_flags = ["nodejs_compat"]

# Routes for both WebSocket and HTTPS endpoints
# WebSocket: /ws/*
# API: /api/*

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-sync-cf-demo"
database_id = "e149c0ac-b08e-4d3f-ac47-09349e47b649"
 
[vars]
# For production, set via CF dashboard as secrets using: wrangler secret put <SECRET_NAME>
# JWT_SECRET = "dev-secret-change-in-production-min-32-chars-long-please"
# GOOGLE_CLIENT_SECRET = "your-google-client-secret" 
# GOOGLE_CLIENT_ID = "your-google-client-id" 
